### ISSUE TITLE
Will not compile when macOS is the Target

### ISSUE THREAD

**Issue by adamhill** [vdshko/DebugFrame#13]
Simple app and added DebugFrame as a package through SPM.

Compiles fine if iOS is the build target (both Build For and Running) but when I try to build for macOS I get errors complaining about macOS 10.15 SwiftUI availability

`'Color' is only available in macOS 10.15 or newer`
`'Overlay' is only available in macOS 10.15 or newer`
`'ZStack' is only available in macOS 10.15 or newer`

etc...

I have checked the 'Deployment Target' in the Project and Default or explicitly setting it to 12.0 for macOS gives the same result.

I did notice that the podspec only has an `.iOS(.v14)`  no `.macOS` entries

Am I missing something obvious?

**Comment by vdshko** [comment]
My bad(( I didn't add all the necessary lines to the spec files. I have done this now, so from 2.2.1, it will be okay. Thanks
